import { ISummaryProps } from '../types/types';
import CONSTANTS from '../constants/constants';

const { ICONS } = CONSTANTS;

/**
 * Creates a DOM node for a summary block using our general format.
 */
const createSummaryBlock = ({
    title,
    subtitle,
    description,
    main,
    footer = 'Generated by Gemini Flash API',
}: ISummaryProps): HTMLElement => {
    const container = document.createElement('div');
    container.className = 'ai-summary-display';
    container.innerHTML = `
        <h5>${title}</h5>
        <h6>${ICONS[subtitle] ?? ''} ${subtitle}</h6>
        <p class="ai-summary-description">${description}</p>
        <div class="ai-summary-main">${main}</div>
        <footer class="ai-summary-footer">-- ${footer}</footer>
      `;

    return container;
};

export default createSummaryBlock;
